//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iCAREEntities : DbContext
    {
        public iCAREEntities()
            : base("name=iCAREEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentMetadata> DocumentMetadatas { get; set; }
        public virtual DbSet<DrugsDictionary> DrugsDictionaries { get; set; }
        public virtual DbSet<GeoCode> GeoCodes { get; set; }
        public virtual DbSet<iCAREAdmin> iCAREAdmins { get; set; }
        public virtual DbSet<iCAREUser> iCAREUsers { get; set; }
        public virtual DbSet<iCAREWorker> iCAREWorkers { get; set; }
        public virtual DbSet<ModificationHistory> ModificationHistories { get; set; }
        public virtual DbSet<PatientRecord> PatientRecords { get; set; }
        public virtual DbSet<TreatmentRecord> TreatmentRecords { get; set; }
        public virtual DbSet<UserPassword> UserPasswords { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
