//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificationHistory
    {
        public int ModificationID { get; set; }
        public Nullable<System.DateTime> DateOfModification { get; set; }
        public string Description { get; set; }
        public string DocID { get; set; }
        public string WorkerID { get; set; }
    
        public virtual DocumentMetadata DocumentMetadata { get; set; }
        public virtual iCAREWorker iCAREWorker { get; set; }
    }
}
