//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRecord
    {
        public int patientID { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public System.DateTime birthdate { get; set; }
        public double height { get; set; }
        public double weight { get; set; }
        public string bloodGroup { get; set; }
        public int bedID { get; set; }
        public string treatmentArea { get; set; }
    }
}
