//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public int passwordID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int passwordExpiryTime { get; set; }
        public Nullable<System.DateTime> userAccountExpiryDate { get; set; }
    }
}
